services:
  trifecta:
    image: berthubert/trifecta
    init: true
    volumes:
      - type: bind
        source: /home/ahu/git/2/trifecta/local-db/
        target: /local-db/
    environment:
      - TRIFECTA_DB=/local-db/trifecta.sqlite
      - TRIFECTA_LOCAL=0.0.0.0
      - TRIFECTA_SMTPSERVER=127.0.0.1:25
      - TRIFECTA_MAILFROM=
      - TRIFECTA_CANURL=
    ports: 
      - "1234:1234"

#    command: --rnd-admin-password
    
